version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: reviews_postgres
    restart: always
    environment:
      POSTGRES_DB: reviews_db
      POSTGRES_USER: reviews_user
      POSTGRES_PASSWORD: reviews_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: reviews_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
